"""Deterministic Gujarat Industrial Corridor Static Seed Data (Ankleshwar - Panoli - Dahej - Jhagadia)

All coordinates are in SRID 4326 (longitude, latitude).
"""

USERS_DATA = [
    {
        "email": "admin@hpee.gov.in",
        "full_name": "Dr. Rajesh Varma",
        "role": "admin",
        "phone_number": "+919825012345",
        "password_hash": "$2b$12$e8Yk1.7zU.7vH4E.PZqU/.Z1ZpQ4u1u.r9Y3k1p5o8E9y6z1y8e6e",  # dummy hashed password
        "is_active": True,
    },
    {
        "email": "sarpanch.piraman@gujaratpanchayat.in",
        "full_name": "Sureshbhai Patel (Sarpanch Piraman)",
        "role": "sarpanch",
        "phone_number": "+919879011223",
        "password_hash": "$2b$12$e8Yk1.7zU.7vH4E.PZqU/.Z1ZpQ4u1u.r9Y3k1p5o8E9y6z1y8e6e",
        "is_active": True,
    },
    {
        "email": "inspector.ankleshwar@gspcb.gov.in",
        "full_name": "Mehul Joshi (Regional Officer GSPCB)",
        "role": "inspector",
        "phone_number": "+919426033445",
        "password_hash": "$2b$12$e8Yk1.7zU.7vH4E.PZqU/.Z1ZpQ4u1u.r9Y3k1p5o8E9y6z1y8e6e",
        "is_active": True,
    },
    {
        "email": "citizen.kiran@gmail.com",
        "full_name": "Kiranbhai Desai",
        "role": "public",
        "phone_number": "+919909055667",
        "password_hash": "$2b$12$e8Yk1.7zU.7vH4E.PZqU/.Z1ZpQ4u1u.r9Y3k1p5o8E9y6z1y8e6e",
        "is_active": True,
    },
]

VILLAGES_DATA = [
    {
        "name": "Ankleshwar GIDC Locality",
        "district": "Bharuch",
        "state": "Gujarat",
        "longitude": 73.0150,
        "latitude": 21.6320,
        "population": 45000,
    },
    {
        "name": "Sanoli",
        "district": "Bharuch",
        "state": "Gujarat",
        "longitude": 73.0020,
        "latitude": 21.6180,
        "population": 8500,
    },
    {
        "name": "Piraman",
        "district": "Bharuch",
        "state": "Gujarat",
        "longitude": 73.0300,
        "latitude": 21.6240,
        "population": 12000,
    },
    {
        "name": "Jitali",
        "district": "Bharuch",
        "state": "Gujarat",
        "longitude": 73.0420,
        "latitude": 21.6450,
        "population": 9200,
    },
    {
        "name": "Dadhal",
        "district": "Bharuch",
        "state": "Gujarat",
        "longitude": 72.9920,
        "latitude": 21.6580,
        "population": 6400,
    },
    {
        "name": "Panoli GIDC Residential",
        "district": "Bharuch",
        "state": "Gujarat",
        "longitude": 72.9640,
        "latitude": 21.5320,
        "population": 18000,
    },
    {
        "name": "Bakrol",
        "district": "Bharuch",
        "state": "Gujarat",
        "longitude": 72.9810,
        "latitude": 21.5450,
        "population": 5800,
    },
    {
        "name": "Kharod",
        "district": "Bharuch",
        "state": "Gujarat",
        "longitude": 72.9490,
        "latitude": 21.5210,
        "population": 7100,
    },
    {
        "name": "Dahej Port Village",
        "district": "Bharuch",
        "state": "Gujarat",
        "longitude": 72.5850,
        "latitude": 21.7120,
        "population": 14000,
    },
    {
        "name": "Rahiyad",
        "district": "Bharuch",
        "state": "Gujarat",
        "longitude": 72.6100,
        "latitude": 21.7300,
        "population": 4900,
    },
    {
        "name": "Jhagadia Township",
        "district": "Bharuch",
        "state": "Gujarat",
        "longitude": 73.1530,
        "latitude": 21.7140,
        "population": 16500,
    },
    {
        "name": "Andada",
        "district": "Bharuch",
        "state": "Gujarat",
        "longitude": 73.0100,
        "latitude": 21.6400,
        "population": 11200,
    },
]

INDUSTRIAL_SITES_DATA = [
    # Ankleshwar GIDC Cluster
    {
        "name": "Gujarat Organics & Dyes Ltd - Plot 401",
        "industry_type": "Dyes & Intermediates",
        "gspcb_consent_id": "GSPCB/CCA-BH-10492/2024",
        "longitude": 73.0185,
        "latitude": 21.6345,
        "address": "Plot 401/402, GIDC Phase II, Ankleshwar",
        "village_name": "Ankleshwar GIDC Locality",
    },
    {
        "name": "Narmada Synthetic Chemicals Pvt Ltd",
        "industry_type": "Specialty Chemicals",
        "gspcb_consent_id": "GSPCB/CCA-BH-11205/2023",
        "longitude": 73.0210,
        "latitude": 21.6310,
        "address": "Plot 512, GIDC Phase II, Ankleshwar",
        "village_name": "Ankleshwar GIDC Locality",
    },
    {
        "name": "Bharuch Pigments & Intermediates Corp",
        "industry_type": "Dyes & Pigments",
        "gspcb_consent_id": "GSPCB/CCA-BH-09881/2024",
        "longitude": 73.0120,
        "latitude": 21.6280,
        "address": "Plot 108, GIDC Phase I, Ankleshwar",
        "village_name": "Sanoli",
    },
    {
        "name": "Apex Agro-Chem Synthesis",
        "industry_type": "Agrochemicals",
        "gspcb_consent_id": "GSPCB/CCA-BH-14562/2025",
        "longitude": 73.0270,
        "latitude": 21.6260,
        "address": "Plot 805, GIDC Phase III, Ankleshwar",
        "village_name": "Piraman",
    },
    {
        "name": "Zenith Pharma Intermediates Ltd",
        "industry_type": "Pharma (Active Ingredients)",
        "gspcb_consent_id": "GSPCB/CCA-BH-13110/2024",
        "longitude": 73.0390,
        "latitude": 21.6420,
        "address": "Plot 920, GIDC Phase IV, Ankleshwar",
        "village_name": "Jitali",
    },
    {
        "name": "Shree Ram Sulphur & Acid Works",
        "industry_type": "Basic Chemicals & Acids",
        "gspcb_consent_id": "GSPCB/CCA-BH-08743/2023",
        "longitude": 73.0160,
        "latitude": 21.6380,
        "address": "Plot 220, GIDC Phase I, Ankleshwar",
        "village_name": "Andada",
    },
    {
        "name": "Sterling Fine Chemicals Ltd",
        "industry_type": "Specialty Chemicals",
        "gspcb_consent_id": "GSPCB/CCA-BH-12940/2024",
        "longitude": 72.9960,
        "latitude": 21.6540,
        "address": "Plot 64, Industrial Extension, Dadhal",
        "village_name": "Dadhal",
    },
    # Panoli GIDC Cluster
    {
        "name": "Panoli Chlor-Alkali & Derivatives",
        "industry_type": "Petrochemicals & Chlor-Alkali",
        "gspcb_consent_id": "GSPCB/CCA-BH-20112/2023",
        "longitude": 72.9680,
        "latitude": 21.5360,
        "address": "Plot 301-305, GIDC Panoli",
        "village_name": "Panoli GIDC Residential",
    },
    {
        "name": "Vanguard Pesticides & Formulations",
        "industry_type": "Agrochemicals",
        "gspcb_consent_id": "GSPCB/CCA-BH-21445/2024",
        "longitude": 72.9780,
        "latitude": 21.5420,
        "address": "Plot 415, GIDC Panoli",
        "village_name": "Bakrol",
    },
    {
        "name": "Shiva Petrochem Refining Additives",
        "industry_type": "Petrochemicals",
        "gspcb_consent_id": "GSPCB/CCA-BH-22980/2024",
        "longitude": 72.9520,
        "latitude": 21.5240,
        "address": "Plot 112, GIDC Panoli",
        "village_name": "Kharod",
    },
    # Dahej PCPIR Cluster
    {
        "name": "Dahej Petrochemical Complex Unit-1",
        "industry_type": "Petrochemicals",
        "gspcb_consent_id": "GSPCB/CCA-BH-30554/2023",
        "longitude": 72.5890,
        "latitude": 21.7160,
        "address": "Plot Z-1, PCPIR SEZ, Dahej",
        "village_name": "Dahej Port Village",
    },
    {
        "name": "Western India Bulk Fertilizers Corp",
        "industry_type": "Fertilizers",
        "gspcb_consent_id": "GSPCB/CCA-BH-31890/2024",
        "longitude": 72.6050,
        "latitude": 21.7280,
        "address": "Plot D-45, Dahej Industrial Zone",
        "village_name": "Rahiyad",
    },
    # Jhagadia Industrial Estate Cluster
    {
        "name": "Jhagadia Specialty Resins & Polymers",
        "industry_type": "Polymers & Resins",
        "gspcb_consent_id": "GSPCB/CCA-BH-40112/2024",
        "longitude": 73.1580,
        "latitude": 21.7190,
        "address": "Plot 701, GIDC Jhagadia",
        "village_name": "Jhagadia Township",
    },
    {
        "name": "United Carbon & Black Works",
        "industry_type": "Carbon & Pigments",
        "gspcb_consent_id": "GSPCB/CCA-BH-41550/2023",
        "longitude": 73.1490,
        "latitude": 21.7100,
        "address": "Plot 812, GIDC Jhagadia",
        "village_name": "Jhagadia Township",
    },
]

SENSOR_NODES_DATA = [
    {
        "node_id": "HPEE-ANK-001",
        "village_name": "Ankleshwar GIDC Locality",
        "longitude": 73.0162,
        "latitude": 21.6335,
        "status": "online",
        "battery_percent": 88.5,
        "signal_strength": -64,
        "sensor_type": "PMS5003_SO2_MET_V1",
    },
    {
        "node_id": "HPEE-ANK-002",
        "village_name": "Sanoli",
        "longitude": 73.0035,
        "latitude": 21.6192,
        "status": "online",
        "battery_percent": 92.0,
        "signal_strength": -68,
        "sensor_type": "PMS5003_SO2_MET_V1",
    },
    {
        "node_id": "HPEE-ANK-003",
        "village_name": "Piraman",
        "longitude": 73.0285,
        "latitude": 21.6255,
        "status": "online",
        "battery_percent": 79.4,
        "signal_strength": -58,
        "sensor_type": "PMS5003_SO2_MET_V1",
    },
    {
        "node_id": "HPEE-ANK-004",
        "village_name": "Jitali",
        "longitude": 73.0410,
        "latitude": 21.6440,
        "status": "online",
        "battery_percent": 84.1,
        "signal_strength": -72,
        "sensor_type": "PMS5003_SO2_MET_V1",
    },
    {
        "node_id": "HPEE-ANK-005",
        "village_name": "Dadhal",
        "longitude": 72.9935,
        "latitude": 21.6570,
        "status": "online",
        "battery_percent": 95.0,
        "signal_strength": -62,
        "sensor_type": "PMS5003_SO2_MET_V1",
    },
    {
        "node_id": "HPEE-ANK-006",
        "village_name": "Andada",
        "longitude": 73.0115,
        "latitude": 21.6392,
        "status": "online",
        "battery_percent": 76.0,
        "signal_strength": -65,
        "sensor_type": "PMS5003_SO2_MET_V1",
    },
    {
        "node_id": "HPEE-ANK-007",
        "village_name": "Panoli GIDC Residential",
        "longitude": 72.9655,
        "latitude": 21.5330,
        "status": "fault",  # Faulty test node
        "battery_percent": 34.0,
        "signal_strength": -89,
        "sensor_type": "PMS5003_SO2_MET_V1",
    },
    {
        "node_id": "HPEE-ANK-008",
        "village_name": "Bakrol",
        "longitude": 72.9825,
        "latitude": 21.5460,
        "status": "online",
        "battery_percent": 91.5,
        "signal_strength": -70,
        "sensor_type": "PMS5003_SO2_MET_V1",
    },
    {
        "node_id": "HPEE-ANK-009",
        "village_name": "Kharod",
        "longitude": 72.9505,
        "latitude": 21.5225,
        "status": "online",
        "battery_percent": 82.3,
        "signal_strength": -66,
        "sensor_type": "PMS5003_SO2_MET_V1",
    },
    {
        "node_id": "HPEE-ANK-010",
        "village_name": "Dahej Port Village",
        "longitude": 72.5865,
        "latitude": 21.7135,
        "status": "online",
        "battery_percent": 89.0,
        "signal_strength": -60,
        "sensor_type": "PMS5003_SO2_MET_V1",
    },
    {
        "node_id": "HPEE-ANK-011",
        "village_name": "Rahiyad",
        "longitude": 72.6115,
        "latitude": 21.7315,
        "status": "online",
        "battery_percent": 90.5,
        "signal_strength": -73,
        "sensor_type": "PMS5003_SO2_MET_V1",
    },
    {
        "node_id": "HPEE-ANK-012",
        "village_name": "Jhagadia Township",
        "longitude": 73.1545,
        "latitude": 21.7155,
        "status": "online",
        "battery_percent": 87.2,
        "signal_strength": -61,
        "sensor_type": "PMS5003_SO2_MET_V1",
    },
]
